title: amx's Homepage
page-top-title: maoxiang an
top-section-bg-text: Don’t overthink. Just move.
home-subtitle: maoxiang an（安茂祥）&ensp;|&ensp;CryptoJoker
copyright-text: '&copy; maoxiang an 2023-2025. All Rights Reserved.'
