title: CryptoJoker's Homepage
page-top-title: CryptoJoker
top-section-bg-text: Don’t overthink. Just move.
home-subtitle: 安茂祥 &ensp;|&ensp;maoxiang an
copyright-text: '&copy; maoxiang an 2023-2025. All Rights Reserved.'
